// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jszujkpqbzclmhfffrgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzenVqa3BxYnpjbG1oZmZmcmd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MDg4MjUsImV4cCI6MjA2NDM4NDgyNX0.nTfxUB40myBe1Zu1V3lKhLxl_Mif_dB5u_hHtkb5VJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);